#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Create employee profiles table."""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "adf82b864267"
down_revision = "512bb8ae048c"
branch_labels = ()
depends_on = "9848d0149abd"


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles_employee",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_address", sa.String(), nullable=False),
        sa.Column("biography", sa.Text(), nullable=False),
        sa.Column("profile_image", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(name="active"), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["accounts_user.id"],
            name=op.f("fk_profiles_employee_id_user_accounts_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles_employee")),
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profiles_employee")
    # ### end Alembic commands ###
